// Isomorphic (browser service-worker + Node) helpers for turning a captured
// AuthFlowSession object into export formats. No chrome.* / fs calls here —
// callers handle I/O so this module works unmodified in the extension and CLI.

/**
 * @param {object} session - matches schemas/session.schema.json
 * @returns {string} pretty JSON
 */
export function sessionToJson(session) {
  return JSON.stringify(session, null, 2);
}

/**
 * @param {object} session - matches schemas/session.schema.json
 * @returns {string} human-readable markdown summary
 */
export function sessionToMarkdown(session) {
  if (!session || !Array.isArray(session.events)) {
    throw new Error("sessionToMarkdown: input does not look like a session (missing events[])");
  }

  const lines = [];
  lines.push(`# Auth-flow session — ${session.target_label || "(unlabeled)"}`);
  lines.push("");
  lines.push(`- Session ID: \`${session.session_id || "unknown"}\``);
  lines.push(`- Started: ${session.started_at_iso || "unknown"}`);
  lines.push(`- Ended: ${session.ended_at_iso || "n/a"}`);
  lines.push(`- Events captured: ${session.events.length}`);
  if (session.notes) {
    lines.push(`- Notes: ${session.notes}`);
  }
  lines.push("");
  lines.push("> Captured metadata only: URL, method, status, resource type, and auth-related **header names**.");
  lines.push("> Header/cookie values are never recorded by this tool.");
  lines.push("");
  lines.push("## Requests");
  lines.push("");
  lines.push("| # | Time | Method | Status | Type | URL | Auth headers (names) | Set-Cookie (names) |");
  lines.push("|---|------|--------|--------|------|-----|-----------------------|---------------------|");

  session.events.forEach((ev, i) => {
    const authHeaders = (ev.auth_header_names || []).join(", ") || "—";
    const cookies = (ev.set_cookie_names || []).join(", ") || "—";
    const url = (ev.url || "").replace(/\|/g, "\\|");
    lines.push(
      `| ${i + 1} | ${ev.timestamp_iso || "?"} | ${ev.method || "?"} | ${ev.status_code ?? "?"} | ${ev.type || "?"} | ${url} | ${authHeaders} | ${cookies} |`
    );
  });

  const authOnly = session.events.filter((e) => (e.auth_header_names || []).length > 0);
  lines.push("");
  lines.push("## Observed auth-related header names (deduplicated)");
  lines.push("");
  const dedup = [...new Set(authOnly.flatMap((e) => e.auth_header_names || []))].sort();
  if (dedup.length === 0) {
    lines.push("_None observed in this session._");
  } else {
    dedup.forEach((h) => lines.push(`- \`${h}\``));
  }

  lines.push("");
  lines.push("---");
  lines.push("_Generated by chrome-mv3-kit / generators/lib/session_export.js. Local artifact — not transmitted off-host by this tool._");
  lines.push("");

  return lines.join("\n");
}

/**
 * Basic structural validation without pulling in a JSON-schema library.
 * Throws with a clear message on the first problem found.
 * @param {object} session
 */
export function assertValidSession(session) {
  if (!session || typeof session !== "object") {
    throw new Error("Invalid session: not an object");
  }
  for (const field of ["session_id", "started_at_iso", "target_label", "events"]) {
    if (!(field in session)) {
      throw new Error(`Invalid session: missing required field "${field}"`);
    }
  }
  if (!Array.isArray(session.events)) {
    throw new Error("Invalid session: \"events\" must be an array");
  }
  session.events.forEach((ev, i) => {
    for (const field of ["url", "method", "auth_header_names", "timestamp_iso"]) {
      if (!(field in ev)) {
        throw new Error(`Invalid session: events[${i}] missing required field "${field}"`);
      }
    }
  });
}
